package memo;

public class SqlCreate {

	/*
CREATE TABLE PARTS(
	ID CHAR(30) NOT NULL ,
        SPEC_ID CHAR(30),
	NAME CHAR(30) NOT NULL,
MATERIAL CHAR(30),
SHAPE CHAR(30),
COLOR CHAR(30),
QUANTITY INT,
UPDATE DATE,
PRIMARY KEY(ID))
	
	
CREATE TABLE VOUCHER(
ID CHAR  NOT NULL ,
DATE DATE NOT NULL,
GOODS_ID CHAR NOT NULL,
GOODS_NAME CHAR NOT NULL,
ISSUE INT  DEFAULT 0,
RECEIPT INT DEFAULT 0,
DESCRIPTION CHAR,
TYPE CHAR,
DONE CHAR(6) DEFAULT 'FALSE', 
PRIMARY KEY(ID)) ;
 
TO_DATE('19-07-01 00:00:00', 'YY-MM-DD HH24:MI:SS')


INSERT INTO VOUCHER
VALUES('v001',TO_DATE('21-12-24 00:00:00', 'YY-MM-DD HH24:MI:SS'),'0001','ダミー',0,100,'清水商店より入庫','入庫',FALSE)
	
	
	*/
}
